name: CI/CD workflow for Dockerized Flask App
# Triggers workflow on the basis of events happening here push or pull to the main branch

on: # Event 1
  push: # Event 1
    branches: [ "main" ]

  pull_request: # Event 2
    branches: [ "main" ]

jobs:
  # Job 0: Build the dockerized application
  Docker-build: 
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v2 # Set up buildx for multi-platform builds
    - name: Build the Docker Image 
      run: docker build . --file DockerFile --tag workflow-test:$(date +%s)

  # Job 1: Build + Test
  build-and-test: # Job: Build + Test
    runs-on: ubuntu-latest # docker container provided by github to run our tests on 
    steps:
    # Step1: Check out our code to the docker container above for testing 
    - name: Checkout Code
      uses: actions/checkout@v4 # prebuilt actions provided by github usage

    # Step2: Setup Python environment for running tests inside docker container 
    - name: Set up Python
      uses: actions/setup-python@v4 # prebuilt actions provided by github usage
      with:
        python-version: "3.10"

    # Step3: Install necessary dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step4: Run our tests
    - name: Run tests
      run: |
        pytest

  # Job 2: Build + Publish
  build-and-publish: # Job: Build + Deploy needs above (Build and Test) job to run first hence we use needs keyword to indicate trigger only when 
    needs: 
        build-and-test # needs this to run first then only build and deploy runs
    runs-on: 
        ubuntu-latest # docker container provided by github to run our tests on 

    steps:
    # 1
    - name: Checkout Code
      uses: actions/checkout@v4 
    # 2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3 # prebuilt actions provided by github usage
    # 3
    - name: Login to Docker Hub
      uses: docker/login-action@v3  
      with:
        # registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    # 4
    - name: Build and push Docker image
      uses: docker/build-push-action@v4

      with:
        context: .
        file: ./DockerFile
        platforms: linux/amd64,linux/arm64,windows/amd64  # Build for multiple platforms
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/flasktest-app:latest # Docker_image_name:tag
    
    # 5 
    - name: Image digest
      run: echo ${{ steps.build-and-publish.outputs.digest }}


